version: '3'

services:
  web:
    build: .
    user: root
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    entrypoint: [/bin/sh, /opt/chatsubo/docker/entrypoint.sh]
    environment:
      - TZ=${CHATSUBO_TZ:-Europe/Paris}
      - BROKER_URL=${CHATSUBO_BROKER_URL:-pyamqp://chatsubo:changeme@rabbitmq//}
      - CHATSUBO_DATABASE_URL=mysql://${CHATSUBO_MYSQL_USER:-chatsubo}:${CHATSUBO_MYSQL_PASSWORD:-chatsubo}@db:3306/${CHATSUBO_MYSQL_DATABASE:-chatsubo}
    volumes:
      - ./config:/opt/chatsubo/config:ro
      - ./docker/uploads:/opt/chatsubo/front/dist/static/uploads:rw
      - /var/chatsubo/docker:/var/chatsubo/docker:ro
    depends_on:
      - db
      - celery
    networks:
      default:
      internal:

  nginx:
    image: nginx:1.19
    restart: always
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - /var/chatsubo/docker:/var/chatsubo/docker:ro
    ports:
      - ${CHATSUBO_PORT:-4545}:80
    depends_on:
      - web

  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - TZ=${CHATSUBO_TZ:-Europe/Paris}
      - MYSQL_ROOT_PASSWORD=${CHATSUBO_MYSQL_ROOT_PASSWORD:-chatsubo}
      - MYSQL_USER=${CHATSUBO_MYSQL_USER:-chatsubo}
      - MYSQL_PASSWORD=${CHATSUBO_MYSQL_PASSWORD:-chatsubo}
      - MYSQL_DATABASE=${CHATSUBO_MYSQL_DATABASE:-chatsubo}
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
    volumes:
      - ./docker/.data/mysql:/var/lib/mysql
    networks:
      internal:

  celery:
    build: .
    user: root
    restart: always
    command: /opt/chatsubo/venv/bin/celery -A app.queue.celery_app worker --concurrency ${MAX_CONCURRENT_CONTAINER_BUILDS:-5} -l INFO
    volumes:
      - ./config:/opt/chatsubo/config:ro
      - /var/chatsubo/docker:/var/chatsubo/docker:ro
    environment:
      - TZ=${CHATSUBO_TZ:-Europe/Paris}
      - BROKER_URL=${CHATSUBO_BROKER_URL:-pyamqp://chatsubo:changeme@rabbitmq//}
      - CHATSUBO_DATABASE_URL=mysql://${CHATSUBO_MYSQL_USER:-chatsubo}:${CHATSUBO_MYSQL_PASSWORD:-chatsubo}@db:3306/${CHATSUBO_MYSQL_DATABASE:-chatsubo}
    depends_on:
      - rabbitmq
      - db
    networks:
      default:
      internal:

  rabbitmq:
    image: rabbitmq:3.8-alpine
    ports:
      - "5672:5672"
    environment:
      - TZ=${CHATSUBO_TZ:-Europe/Paris}
      - RABBITMQ_DEFAULT_USER=chatsubo
      - RABBITMQ_DEFAULT_PASS=changeme
    logging:
      driver: none
    networks:
      default:
      internal:

networks:
  default:
  internal:
      internal: true
